language: node_js

sudo: required

node_js:
  - "10.16.0"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn run ganache &
  - yarn run migrate
  - yarn run test
  - yarn run lint